### ISSUE TITLE
Painting issue with COMMON_LVB_UNDERSCORE in 1703 onwards

### ISSUE THREAD

**Issue by dra27** [Microsoft/console#47] opened 2018-01-08 11:34 UTC
`COMMON_LVB_UNDERSCORE` seems to paint unreliably since Windows 10 1703 (10.0.15063) and it's still present in 10.0.17063.1000 on the fast insider ring.

Compile and run the following program multiple times from a new command prompt (I've only tried it on x64 installations):

```c
#include <windows.h>
#include <stdio.h>

int main(void) {
  HANDLE hConsole = GetStdHandle(STD_OUTPUT_HANDLE);
  CONSOLE_SCREEN_BUFFER_INFO info;
  GetConsoleScreenBufferInfo(hConsole, &info);
  SetConsoleTextAttribute(hConsole, COMMON_LVB_UNDERSCORE | info.wAttributes);
  printf("COMMON_LVB_UNDERSCORE added to console text attributes\n");
  fflush(stdout);
  printf("Hello world\n");
  fflush(stdout);
  SetConsoleTextAttribute(hConsole, info.wAttributes);
}
```

The expected output is two lines of text both underlined. On my 1703 box, the first line is never underlined and, randomly, neither was the second on one run. Scroll the console to move the lines off-screen and scroll it back and the lines reappear.

Note that you have to scroll the console text itself out of the viewport and back in - moving another window over the top of the console and then off does not cause the underlining to reappear. The effect occurs regardless of whether the program is run from the machine directly or via remote desktop.

**Comment by zadjii-msft** [comment] 2018-01-11 17:25
I'm gonna link Maximus5/ConEmu#1302 to this, because they definitely look related. In all likelyhood I probably messed something up with meta attributes when I added RGB color.

I'm looking into it.

**Comment by DHowett-MSFT** [comment] 2018-10-25 17:50
This is fixed in the "October 2018 Update".

**Closed by DHowett-MSFT** 2018-10-25 17:50 UTC
Labels: bug, conhost

**Comment by scrouthtv** [comment] 2021-03-13 07:26
@DHowett-MSFT `COMMON_LVB_UNDERSCORE` is not working for me. Should I open a new issue?

I am running 1.7.572.0

**Comment by zadjii-msft** [comment] 2021-03-15 15:44
@scrouthtv Probably - this bug is just about 3 years old (and entirely predates the Terminal's entire codebase), so if you're seeing something like this, it's probably a different root cause.

**Comment by DHowett** [comment] 2021-03-15 16:23
I believe we decoupled `COMMON_LVB_UNDERSCORE` from SGR 4 underline, and now Terminal therefore ignores `COMMON_LVB_UNDERSCORE`.

**Comment by scrouthtv** [comment] 2021-03-15 16:27
I just found there's already an opened issue about this: #8037
