### ISSUE TITLE
make menuconfig in WSL doesn't look right

### ISSUE THREAD

**Issue by naikrovek** [Microsoft/console#316] opened 2018-12-05 12:50 UTC
Windows Build `Microsoft Windows [Version 10.0.17763.134]`

Building linux kernels using `make menuconfig` is functional and produces slight gibberish in the console.  Attached should be screenshots of the console and xterm after launching `make menuconfig` in the linux kernel repository as pulled from github.  (`git clone https://github.com/torvalds/linux` then `cd linux` and finally `make menuconfig` to reproduce what I've done.

I've tried to make the font sizes similar between WSL and Windows and in the interests of time I stopped with the fonts you see in the screenshots.

The WSL console produces this:
![image](https://user-images.githubusercontent.com/284498/49514332-5cf2e480-f859-11e8-9b0e-63660c1ce9ab.png)

This is what it should look like (ignore the difference in font.)
![image](https://user-images.githubusercontent.com/284498/49514347-6bd99700-f859-11e8-84af-17951bf9a546.png)

I have no idea what VT sequences are not being handled or what's going on, I just noticed that it didn't look right.

This is probably a duplicate of #208 however I don't see exactly the same behavior as the animation in that bug, so maybe this deserves its own bug.  Close it if it's a duplicate.

**Comment by zadjii-msft** [comment] 2018-12-05 17:02
I'm pretty sure this is a dupe of #240, and part of #208 is definitely #240 as well. That should be already fixed in Insiders :)

**Closed by zadjii-msft** 2018-12-05 17:02 UTC
