### ISSUE TITLE
Starting another process causes underlining to disappear

### ISSUE THREAD

**Issue by dra27** [Microsoft/console#48] opened 2018-01-08 11:46 UTC
This seems to be present since RTM (tried on 1503, 1511, 1607, 1703, 1709 and fast insiders ring).

Run any program from a command prompt which displays underlined text (for example, the program in #47), but also using the 1511 ANSI support:

```c
#include <windows.h>
#include <stdio.h>

int main(int argc, char** argv) {
  HANDLE hConsole = GetStdHandle(STD_OUTPUT_HANDLE);
  DWORD dwMode;
  GetConsoleMode(hConsole, &dwMode);
  SetConsoleMode(hConsole, dwMode | ENABLE_VIRTUAL_TERMINAL_PROCESSING);
  printf("\e[4mHello world\e[0m\n");
  SetConsoleMode(hConsole, dwMode);
}
```

Running this a few times gets some lines of text on the console which are underlined. I noticed when running some other processes that underlining from previous text temporarily disappears while they're running (for example, the `pscp` command from the PuTTY suite or OCaml's toplevel prompt `ocaml`). When those processes exit, the underlining of the previous text suddenly reappears.

If you then enter `cmd` to start a nested interpreter, then the underlining disappears from the previous text permanently (i.e. it doesn't even reappear when you type `exit` from the nested interpreter).

I'm not aware of any of those programs intentionally manipulating the attributes of the console cells, so I think it's reasonable to expect that the underlining should be persisting!

**Comment by zadjii-msft** [comment] 2018-01-11 17:27
I'm gonna close this issue because it's basically a dupe of #47.

**Closed by zadjii-msft** 2018-01-11 17:27 UTC

**Comment by dra27** [comment] 2018-01-11 17:45
Your call, as the keeper of the code, obviously! The only thing from my perspective is that this one affects all releases of Windows 10 but #48 is only 1703+
