### ISSUE TITLE
colortool: inconsistent color with iterm2

### ISSUE THREAD

**Issue by yatli** [Microsoft/console#59] opened 2018-02-06 04:21 UTC
build 16299, using colortool from https://github.com/Microsoft/console/commit/e0248749eb0874a61975109f7d09bfe8246ee92a

Repro: 
- clone the iTerm2-Color-Schemes repo from https://github.com/mbadolato/iTerm2-Color-Schemes
- use colortool to apply a scheme, say `Argonaut`
- compare the console colors with the colors in the iTerm2 color schemes repo screenshots

Expect:
- same colors

Actual:
- different colors

Comparison:
![image](https://user-images.githubusercontent.com/20684720/35841484-26d673b8-0b37-11e8-9da5-52a467a7a068.png)
Note how some of the values differ subtly with the original. Especially for the grey colors. Some are swallowed in the background.

Possibly related to the color space? In iterm2 xml the rgb components are companioned with a color profile (sRGB etc.)

Also, we should parse the foreground & background colors and set them in the console.

A more drastic example:
![image](https://user-images.githubusercontent.com/20684720/35841655-17aa22bc-0b38-11e8-844d-6d5be78556a8.png)

This one should be due to missing background & foreground.

**Comment by zadjii-msft** [comment] 2018-02-12 22:06
This has been discussed before on #23.

Essentially, the console doesn't have a seperate "Background Color" seperate from the color table - it uses one entry of the color table as it's "background color". So if the itermcolors scheme has a different background color from the black color, then the applied scheme is going to look different. It's as close as we can get to what's in the scheme with what conhost can do.

I absolutely want to fix this, but unfortunately its a pretty massive change to the codebase that'd be hard to get signed off on.

I'm going to close this isse as a dupe of the other, and use the other one for tracking the feature.

**Closed** 2018-02-12 22:06 UTC
Labels: conhost, duplicate, feature
