### ISSUE TITLE
1809 PowerShell - Ctrl-L clears the screen, but next keystroke brings text back

### ISSUE THREAD

**Issue by AdamDotNet** [Microsoft/console#302] opened 2018-11-06 20:27 UTC
* Your Windows build number:  10.0.17763.55

* What you're doing and what's happening: Open PowerShell, type in a few commands, and then clear the screen with `ctrl-L`. The text will disappear. Type anything else, and the cleared text comes back onto the screen.

* What's wrong / what should be happening instead: Cleared text should remain cleared.

![windows powershell 2018-11-06 13-19-44](https://user-images.githubusercontent.com/8978001/48091658-8a4f6280-e1c7-11e8-8a26-0b29c3ef29d3.gif)

**Comment by Delivator** [comment] 2019-02-03 10:09
Any workaround/fix for this?

**Comment by The-Honey-Badger** [comment] 2019-02-06 03:48
I've been experiencing this for a while now. Would absolutely LOVE a fix.

**Comment by fungiboletus** [comment] 2019-02-18 08:55
A workaround mentioned in some linked issues is to switch to a qwerty keyboard layout, like the US because obviously the testers forgot to test with various keyboard layouts, and once the console has started you can switch back to your normal layout (azerty, dvorak, bépo…).

**Comment by zadjii-msft** [comment] 2019-02-19 16:05
I'm actually 80-90% sure that this is caused by the same root cause as #270, and that fix should be in insiders currently.

For the record, one of the console devs actually does use Coleman as his keyboard layout, so yes, we do test other layouts😜
________________________________

**Comment by The-Honey-Badger** [comment] 2019-04-28 14:41
Any update on this?? Still having the issue on 1809 Build 17763.437 with PSVersion 5.1.17763.316 and would really like a workaround/patch given that I've been experiencing this bug since October of 2018... I'm willing to do just about anything to bring back my CTRL+L. I've tried to re-create the CTRL+L function manually via the following custom PSReadLineKeyHandler chord:

```
Set-PSReadLineKeyHandler -Chord Ctrl+Shift+B -ScriptBlock {
	$line = $null
	$cursor = $null
	#get the current line
	[Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
	[Microsoft.PowerShell.PSConsoleReadLine]::BackwardKillLine()
	[Microsoft.PowerShell.PSConsoleReadLine]::ClearScreen()
	[Microsoft.PowerShell.PSConsoleReadLine]::Insert($line)
}

```
However this does not work, so I tried replacing ClearScreen() with the Clear-Host cmdlet but that will just clear the screen but the cursor buffer stays in the same spot. Looking into it further, it looks like the real problem is from the [Microsoft.PowerShell.PSConsoleReadLine]::ScrollDisplay* function which (as far as I can tell) does absolutely nothing. Not sure where to go from here, but hopefully this gets fixed soon.

**Comment by zadjii-msft** [comment] 2019-04-29 13:34
@The-Honey-Badger The fix for this bug is in Windows 1903 - See #270 for more details.

**Closed by zadjii-msft** 2019-04-29 13:34 UTC
Labels: Powershell

**Comment by Delivator** [comment] 2019-04-29 14:07
I'm on 1809 too and still have this problem. A friend of mine just installed Windows 10 a few days ago and it still had the bug.

**Comment by j0rdan0** [comment] 2023-10-22 16:16
This is still happening on:

OS Name:                   Microsoft Windows Server 2019 Datacenter
OS Version:                10.0.17763 N/A Build 17763

Any fixes for this bug for this version it is very annoying, especially for someone coming from Linux environment where CTRL-L always worked for clearing screen.

**Comment by DHowett** [comment] 2023-10-23 17:08
I'm sorry. Fixes for bugs like this don't meet the relatively high bar for servicing to versions of Windows that are that old.

**Comment by upd4t3yourf1rmware** [comment] 2024-04-01 02:01
cls - old clear working in this case)
