### ISSUE TITLE
Can't properly install Zsh in Ubuntu for Windows 

### ISSUE THREAD

**Issue by feinstein** [Microsoft/console#393] opened 2019-03-25 14:39 UTC
I installed Ubuntu on the WSL and wanted to install Zsh as my new bash. 

The problem is, when I select a theme like agnoster, all the characters and colors are wrong. I think it's because the console doesn't provide all the colors and the powerline font installed in Ubuntu is ignored.

Can you guys fix this? 

(or even be more amazing and copy Zsh for Window, so we can have all the plug-ins and themes?)

**Comment by bitcrazed** [comment] 2019-03-25 18:30
Hey @feinstein.

Alas, Windows Console (the "Terminal" UX you see when running distros atop WSL) doesn't yet support displaying glyphs not contained in the currently selected font. Nor does it know how to render extended unicode glyphs like emoji, etc. We are actively working to remedy this for future OS releases.

Re. colors, if your colors are wrong, you'll have to either update your prompt's color VT sequences to specify specific RGB colors, or update your Console's palette to match the colors you expect for each color index.

I'm closing this issue as a dupe of the following issues over in the Console issues repo:
* https://github.com/Microsoft/console/issues/190
* https://github.com/Microsoft/console/issues/387

**Closed by bitcrazed** 2019-03-25 18:30 UTC
Labels: conhost, duplicate, rendering

**Comment by feinstein** [comment] 2019-03-25 18:35
Hi @bitcrazed,

So if I understand this correctly, a Zsh theme won't ever work... I have to set all the colors myself on the console? This is a bit limiting to be honest :/

**Comment by feinstein** [comment] 2019-03-26 22:47
just as a reference, this is what I would like to have on my WSL Ubuntu:
https://github.com/agnoster/agnoster-zsh-theme
