### ISSUE TITLE
ncurses rendering issue under wsl/ubuntu

### ISSUE THREAD

**Issue by tenox7** [Microsoft/console#263] opened 2018-09-28 06:18 UTC
* Your Windows build number:  Microsoft Windows [Version 10.0.17134.285]

* What you're doing and what's happening: Under WSL/Ubuntu/18.04 this simple ncurses code should display 5 x characters.

```
#include <stdio.h>
#include <curses.h>

int main(int argc, char *argv[]) {
    int i;
    initscr();
    erase();
    for(i=0; i<5; i++)
        mvaddch(0, i, 'x');
    refresh();
    getch();
    endwin();
```

* What's wrong / what should be happening instead:

Only one x character is displayed.
5 x characters should be displayed.

Note that this is problem with Windows Console specifically. When running over wsl-bridge (eg wsltty or wsl-terminal) this works correctly.

**Comment by zadjii-msft** [comment] 2018-09-28 16:45
I'm fairly certain this is a dupe of #240

**Closed by zadjii-msft** 2018-09-28 16:45 UTC
Labels: conhost, duplicate, feature
