### ISSUE TITLE
Emacs terminal interface in WSL / SSH is broken in 1809

### ISSUE THREAD

**Issue by vlj** [Microsoft/console#318] opened 2018-12-06 11:06 UTC
I added the same comment to feedback Hub, I don't know if it's more efficient to use github or the feedback hub.

In 1809 when launching emacs from WSL (it's available with Ubuntu image + apt install emacs) or through ssh in CMD.exe/PowerShell to a remote Mac/OSX, the terminal interface is broken : when a line is "big enough" (like 20 characters long), moving the caret to the right randomly skip letters. CTRL + E (shortcut to go to the end of the line) also skip characters. Scrolling is also producing random garbage letters at random location. Editing files is practically impossible.

Note that it's likely that others editor are concerned too but I didn't test them.

It worked properly with 18.03

**Comment by oising** [comment] 2018-12-06 16:05
I can verify on WSL, win10 build 18290 (latest insider on fast). 

The issue is best demonstrated by holding down the right arrow key. The cursor skips erratically back and forth, up and down. 

The issue goes away with `$TERM` set to `xterm-color` -- it's only happening with `xterm-256color`. That's as far as I dug in.

@vlj -- run `export TERM=xterm-color` and the issue goes away (at least on build 18290)

**Comment by zadjii-msft** [comment] 2018-12-06 17:35
Please search before filing new issues - this is definitely a dupe of #283

**Closed by zadjii-msft** 2018-12-06 17:35 UTC
Labels: conhost, duplicate
