### ISSUE TITLE
Snake game written in Bash has no snake or color

### ISSUE THREAD

**Issue by mobluse** [Microsoft/console#356] opened 2019-01-19 22:26 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.17134.556]

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)
`bash snake`

* What's wrong / what should be happening instead:
The snake is hardly shown. In WSL, no color. In WSLTTY 1.9.5 there is color. This bash game works perfectly in Raspbian Stretch and Lubuntu 16.04.
It should look like (i.e. with color and snake): http://wp.subnetzero.org/?p=269
The Bash source is there too. I just copied it into `nano` and used exactly the same file in all computers.

**Comment by DHowett-MSFT** [comment] 2019-01-21 22:46
This is an interesting case. It looks like your distribution might be missing the termcap files for our declared terminal type, `xterm-256color`.

If you run `TERM=xterm ./snake.sh` (or whatever you've named the script), do you get colors and/or a snake?

A more constrained repro case would be:

```
tput setf 4 | cat -v
```

On Debian `buster/sid`, I get:

```
% tput setf 4 | cat -v
% # (nothing)  
```

However, if I use `TERM=xterm`, I get:

```
% TERM=xterm tput setf 4 | cat -v
^[[31m
%
```

If the termcap for xterm-256color is missing or incomplete (which is a distribution issue), `tput` won't produce any output, and the color won't be changed.

**Comment by j4james** [comment] 2019-01-22 00:37
I'm no expert, but my understanding was that terminals aren't necessarily expected to support both `setf` and `setaf` - just the one or the other. If you look at xterm+256color entry in [the current terminfo source](https://invisible-island.net/datafiles/current/terminfo.src.gz), you can see that the `setf` and `setb` capabilities are explicitly suppressed - you're expected to use `setaf` and `setab` instead.

So I don't think there's anything wrong with the termcap entry - I think the problem is with the snake script for assuming that `setf` would work on all terminals when that is quite often not true.

**Comment by DHowett-MSFT** [comment] 2019-01-22 00:39
@j4james Great call! I wasn't aware that it might support one and explicitly suppress the other.

In light of that, I'm closing this as **external** -- the onus is on `snake` to use the right terminal capabilities. There's a trivial workaround in terms of setting `TERM`, as well.

**Closed by DHowett-MSFT** 2019-01-22 00:39 UTC

**Comment by mobluse** [comment] 2019-01-22 15:46
`XTERM=xterm ./snake` in Ubuntu 18.04 from Store fixes the color, but the snake works in a strange way and 'SIZE=3' is printed several times within the playing field.
