### ISSUE TITLE
Supplementary Multilingual Plane characters

### ISSUE THREAD

**Issue by cup** [Microsoft/console#321] opened 2018-12-08 20:24 UTC
Windows 10 October 2018 Update (build 1809) is supposed to finally allow the
console to support SMP (4 byte) characters:

http://blogs.msdn.microsoft.com/commandline/2018/11/15/windows-command-line

However in practice it is not working for me. I created a virtual machine:

http://microsoft.com/software-download/windows10ISO

and utilizing this character:

    U+10480 OSMANYA LETTER ALEF
    𐒀

http://fileformat.info/info/unicode/char/10480/index.htm

the output is 4 bytes 0xF0 0x90 0x92 0x80, which is displayed as 2 invalid
characters U+D801 and U+DC80 (surrogate pair) rather than a single valid
character U+10480. Am I doing something wrong or is this still not supported by
Windows console?

**Comment by DHowett-MSFT** [comment] 2018-12-08 20:40
The console in 1809 can _store_ SMP codepoints, but it cannot yet render them. Doing something about our legacy GDI renderer (which doesn't support much beyond UCS-2) is on our backlog.

A quick test would be to copy those two invalid characters into another application. When I do that, I get this (where my "other application" is the Run dialog):

![image](https://user-images.githubusercontent.com/14316954/49690471-6fce1900-fae6-11e8-9f2a-ee2bce9f48e6.png)

**Comment by zadjii-msft** [comment] 2018-12-11 18:53
This is effectively a dupe of #190.

**Closed by zadjii-msft** 2018-12-11 18:53 UTC

**Comment by cup** [comment] 2019-03-23 14:16
https://github.com/Microsoft/console/issues/327
