### ISSUE TITLE
Colortool changes default but not current, and defaults aren't used in new window

### ISSUE THREAD

**Issue by tdalpert** [Microsoft/console#257] opened 2018-09-18 23:14 UTC
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
17134.286

* What you're doing and what's happening: (Copy & paste specific commands and their output, or include screen shots)

* What's wrong / what should be happening instead:
colortool won't update the current color scheme. I've tried -d for defaults and -b both and restarted the terminal window plenty. When I right click and select defaults, the color scheme is changed! But the terminal isn't seeming to use the defaults. I just installed WBL and updated all packages, so there shouldn't have been too much room for error yet.
I have manually played with changing the preferences before I installed colortools. 
![colors](https://user-images.githubusercontent.com/13370787/45721560-7ba8df80-bb76-11e8-88a5-1755c1f9e0cb.jpg)

using colortool v1.0.0.0

**Comment by zadjii-msft** [comment] 2018-09-19 16:10
Okay I just double checked, PR #50 will resolve #22 even in conpty builds of WSL. I'll close this issue as a dupe of 22.

**Closed by zadjii-msft** 2018-09-19 16:10 UTC
Labels: colortool, duplicate
