### ISSUE TITLE
Text is not being rendered properly while running Emacs on WSL

### ISSUE THREAD

**Issue by utsavgupta** [Microsoft/console#354] opened 2019-01-19 13:21 UTC
* Your Windows build number:  10.0.17763.253

* What you're doing and what's happening:  After upgrading to this version of Windows, Emacs seems to have been broken. The text is not being rendered correctly. Kindly have a look at the minibuffer in the attached screenshot. This issue was reproducible on command line, cmder, and hyperjs.

![emacs-wsl](https://user-images.githubusercontent.com/291183/51427220-44793680-1c1b-11e9-8425-3283627a92bb.png)

**Comment by miniksa** [comment] 2019-01-22 16:50
@zadjii-msft, this feels like #283. Can you confirm?

**Comment by zadjii-msft** [comment] 2019-01-22 17:33
I'd be fairly confident that issue is the same as this one, though I'm not totally sure what emacs is supposed to look like here, only that it's "not correct".

@utsavgupta can you give me exact keypresses (and other needed repro steps) to get into the state you're seeing the buggy rendering, so I can confirm it's fixed in Insiders?

**Comment by utsavgupta** [comment] 2019-01-22 18:19
@zadjii-msft Yes I can confirm that it is the same #283. Not correct as in the cursor keeps jumping as shown in the GIF attached with the the related issue. Can you please tell me when will the fix be available ?

Thanks.

**Comment by zadjii-msft** [comment] 2019-01-22 18:22
Thanks for confirming it's the same as the other issue, I'll close this one as a dupe.

As per the other thread:
> This is fixed in Insiders 18309 and higher.

**Closed by zadjii-msft** 2019-01-22 18:22 UTC
Labels: conhost, duplicate, rendering
