### ISSUE TITLE
more erratic curser problems

### ISSUE THREAD

**Issue by saraheno** [Microsoft/console#382] opened 2019-03-05 03:27 UTC
I am having problems like the ones described in https://github.com/Microsoft/console/issues/283.  This is marked closed, but I have the problem in the latest release.  You can see the detailed description in my post at the bottom of this closed issue.

**Comment by zadjii-msft** [comment] 2019-03-05 16:43
I'm closing this issue as a dupe of #283, see my response in that thread.

**Closed by zadjii-msft** 2019-03-05 16:43 UTC
Labels: duplicate
