### ISSUE TITLE
strange behaviour after ubuntu ugrade

### ISSUE THREAD

**Issue by florian1984** [Microsoft/console#188] opened 2018-05-23 05:35 UTC
After Upgrade to:

Distributor ID: Ubuntu
Description: Ubuntu 16.04.4 LTS
Release: 16.04
Codename: xenial

OS Release:  Microsoft Windows 10 Pro  10.0.17134 Nicht zutreffend Build 17134

I've some strange behaviour when connection to other rhel7/sles boxes over ssh.

vi: cursor keys no longer working page up/down works without problem
vim: cursor keys working but page up/down not working

I could fix cursor keys in vi with : :set term=builtin_ansi, but this behaviour started after upgrade. :(. On local session vi works normal...

Thanks for any hints.

**Comment by DarthSpock** [comment] 2018-05-23 14:12
Remove export TERM=xterm-color from  ~/.bash_profile from the remote machine and try again.
Ref:  #139

**Comment by zadjii-msft** [comment] 2018-05-23 15:40
I'm gonna close this as a dupe of #139. If what @DarthSpock mentioned doesn't work, feel free to re-open it.

**Closed by zadjii-msft** 2018-05-23 15:40 UTC

**Comment by florian1984** [comment] 2018-05-24 05:05
Hi DarthSpock, on Linux boxes (rhel7) cursor keys working after unset TERM. But PageUp/Down still not working. On AIX it mess up the whole terminal after unset TERM :-).
