### ISSUE TITLE
Auto-complete does not work when opening cmd.exe/powershell.exe from WSL.

### ISSUE THREAD

**Issue by MahdiGhiasi** [Microsoft/console#228] opened 2018-07-30 10:08 UTC
When opening cmd.exe or powershell.exe from WSL, Auto-complete (tab key) does not work in the opened cmd/powershell process. It types a tab character instead.

* My Windows Build Number: 17134.165

* Tested WSL version: Ubuntu 16.04 and Ubuntu 18.04

* Expected behavior: Tab key should suggest based on file names on current directory, just like a cmd.exe/powershell.exe opened directly from start menu does.

* What's happening: Tab key types a \t character on screen instead of auto-completing, when running cmd.exe or powershell.exe from bash.

* Steps to reproduce:

1. Open a bash Window.

2. Type cmd.exe (or powershell.exe) and press enter.

3. Type a character and press tab button.

* GIF showing the issue:

![2018-07-30_14-36-01](https://user-images.githubusercontent.com/1775637/43391538-24758ee4-9406-11e8-8f0a-24850dd1f5ca.gif)

**Comment by zadjii-msft** [comment] 2018-07-30 15:53
This is a dupe of a bunch of issues that are all fundamentally fixed by #57, which is already available in Insiders.

**Closed by zadjii-msft** 2018-07-30 15:53 UTC
