### ISSUE TITLE
Deleting characters or lines in WSL editors (nano/vi) cause display issues

### ISSUE THREAD

**Issue by darrenmonahan** [Microsoft/console#214] opened 2018-07-04 01:25 UTC
Windows build: Started in 17692 and still present in 17704. Was not present in 17686.

Open WSL and open a text file at least one page worth of text, such as .bashrc, with nano or vi. Delete a line midway through and you should notice that the console window will appear to clear usually entirely. This also can occur when using the backspace or delete keys (although that only partially clears the window).

I am able to 100% reproduce this in multiple consoles: Bash for Windows, Visual Studio Code's terminal, and Terminus, and can confirm that if I rollback to 17686 it no longer occurs.

Screenshots available on the Feedback Hub: https://aka.ms/AA1pjqq - I do not appear to have access to get that back, I'm afraid, but I can create new ones if they aren't available.

**Comment by zadjii-msft** [comment] 2018-07-05 15:54
This looks like another dupe of #210. It's already fixed and on it's way out to Insider's.

**Closed** 2018-07-05 15:59 UTC
Labels: duplicate
