### ISSUE TITLE
broken vertical line char

### ISSUE THREAD

**Issue by Ansuel** [Microsoft/console#194] opened 2018-05-26 11:05 UTC
* Your Windows build number:  Microsoft Windows [Versione 10.0.17677.1000]

* What you're doing and what's happening: make menuconfig command

 
![cattura](https://user-images.githubusercontent.com/20289090/40575412-ea9f10ae-60e4-11e8-885d-13b9059d1724.PNG)

* What's wrong / what should be happening instead: as you can see from the screen, the vertical line char is broken and not displayed.  Trying to paste it to a nano editor doesn't show anything, trying with other works... For example this is displayed ├ but this not ─

**Comment by zadjii-msft** [comment] 2018-05-29 16:50
What font is that?

This certainly smells like a dupe of #189 to me.

**Comment by Ansuel** [comment] 2018-06-06 19:37
any news for this?

**Comment by zadjii-msft** [comment] 2018-06-06 19:39
Nope, I'll post an update when I make progress on this.

**Comment by DHowett-MSFT** [comment] 2018-10-03 20:15
Oh, this is another case of #240. Marking duplicated!

**Closed by DHowett-MSFT** 2018-10-03 20:15 UTC

**Comment by DHowett-MSFT** [comment] 2018-10-03 20:17
As a workaround, you can set your `TERM` to `vt100` or `putty` (if your distribution provides a putty termcap.) The `putty` terminal definition is _almost exactly `xterm-256color`_ but it doesn't offer "repeat graphic character", the behavior _dialog_ is using.

**Comment by Ansuel** [comment] 2018-10-03 20:20
sorry but where should i set the TERM variable?
