### ISSUE TITLE
Add  fallback fonts to display  more Unicode codepoints

### ISSUE THREAD

**Issue by musm** [Microsoft/console#403] opened 2019-04-01 02:46 UTC
A lot of modern languages such as Julia heavily use math symbols. Without fallback fonts it's very hard to find font that has all the code points needed to properly render all the math fonts and emojis.  Consolas doesn't have  broad Unicode coverage, but with font fallbacks this can be improved.

**Comment by DHowett-MSFT** [comment] 2019-04-01 04:54
This'll be a duplicate of #190, with a bit of #387 mixed in.

**Closed by DHowett-MSFT** 2019-04-01 04:54 UTC
Labels: duplicate

**Comment by musm** [comment] 2019-04-02 02:06
Not related to https://github.com/Microsoft/console/issues/387,  that's a font issue, but I suppose is a dupe of #190. Although the issue is not really focused on emojis.   In fact, there's a greater importance than suggested 
by issue #190, since it's quite annoying when certain math symbols are not rendered in the terminal leaving you guessing as to what the code is doing.    
I'd prefer the approach editors such as vs-code  take, where you can specify a chain of fonts.

**Comment by miniksa** [comment] 2019-04-02 02:09
Sorry, @musm, for us it's the same thing. If we want to get emoji, we need to support font fallback. If we get font fallback, it should work for your codepoints too, not just emoji. So we're tracking this all under the same issue.

**Comment by musm** [comment] 2019-04-02 02:12
@miniksa  thanks for the clarification. Good luck and keep up the awesome work on console features.
