### ISSUE TITLE
Unicode characters not rendering correctly in console

### ISSUE THREAD

**Issue by wolf99** [Microsoft/console#222] opened 2018-07-13 08:14 UTC
* Your Windows build number:  Version 1709 (OS Build 16299.431)

* What you're doing and what's happening: 
There are some Unicode characters (e.g. ☀) that I've noticed do not work in the default console font (Consolas) in the console.
These same characters work in with the same font in other placers (e.g. Notepad).
I've tried another font, such as DejaVu Sans Mono, but with the same result.

* What's wrong / what should be happening instead: The characters should all display as intended

In WSL console the character doesn't appear at all.

![image](https://user-images.githubusercontent.com/281700/42692682-5eba5e46-86a4-11e8-8089-85251ace15b0.png)

![image](https://user-images.githubusercontent.com/281700/42692567-0a02011a-86a4-11e8-91bd-a942c9f79e95.png)

**Comment by zadjii-msft** [comment] 2018-07-13 14:56
This is a dupe of #190.

**Closed by zadjii-msft** 2018-07-13 14:56 UTC
