### ISSUE TITLE
WSL console black-on-black cursor in 17713.rs5

### ISSUE THREAD

**Issue by bbulkow** [Microsoft/console#232] opened 2018-08-08 19:05 UTC
I tried loading this bug in the WSL area... they summarily closed and told me to go here. I don't know exadtly where you think WSL stops and console begins, and it's a little frustrating to do free QA for you when I can't even tell where bug reports go.

I installed 17713.rs5 off the early access program, and it's difficult to use with WSL because the cursor is black instead of grey. I can see the cursor is there, because it occludes a few bits of the font.

This is true on the three WSLs I have loaded - Ubuntu 18.04, Ubuntu 16.04, and Debian.

I have an LS_COLORS set of ow=01;36;40 , if that makes a difference. I am not using any of the techniques to change the cursor. Until .rs5 I saw a cursor just fine.

You're welcome for the bug report!

**Comment by zadjii-msft** [comment] 2018-08-08 19:15
This is a dupe of #193, #200, #225, etc. 

Various fixes are inbound or already in Insiders.

**Closed by zadjii-msft** 2018-08-08 19:15 UTC

**Comment by bbulkow** [comment] 2018-08-10 21:50
That bug is claimed to be fixed in 

This is fixed in Insiders 17683 and higher

As quoted in the title, I am running higher.

Thus, I am re-opening --- do I need to do something?

**Comment by DHowett-MSFT** [comment] 2018-08-10 22:03
We found a couple more issues in this area. The fix for the last of those issues will probably be in the _next_ insider build.
